[serve]
# The address to serve on LAN.
address = "127.0.0.1"
# The address to serve on WAN.
# address = "0.0.0.0"
# The port to serve on.
port = 8080

[[proxy]]
backend = "http://127.0.0.1:8000/api"

[build]
target = "index.html"
dist = "dist"

[[hooks]]
stage = "build"
command = "sh"
command_arguments = ["-c", "tailwindcss -i ./assets/input.css -o ./assets/css/tailwind.css || true"]
